### ISSUE TITLE
How do Chinese users connect and access code?Or Mimic has not been opende to China.

### ISSUE THREAD

**Issue by wodiao2010** [molenzwiebel/Mimic#17]

**Comment by ghost** [comment]
使用的域名conduit疑似被dns污染也没有icp证 

你用什么互联网线路? 什么城? 



我看电信线路污染
rift.mimic.lol has address 199.16.156.7
rift.mimic.lol has address 75.126.150.210
rift.mimic.lol has address 66.220.149.99

**Comment by wodiao2010** [comment]
不知道什么原因...

**Comment by molenzwiebel** [comment]
Mimic is routed through Cloudflare and should be normally accessible in China. If it is DNS polluted or otherwise not available, there's unfortunately nothing I can do.
