### ISSUE TITLE
Ins't the 6 digit code easily brute-forceable? 

### ISSUE THREAD

**Issue by Warix3** [molenzwiebel/Mimic#26]
The code doesn't seem to be for one-time use, so I think it can be easily brute forced to access someone's client. To counter this I recommend to make the code expire as soon as someone activates it.

**Comment by molenzwiebel** [comment]
You are correct in that the code is easily brute-forceable. However, note that just a 6-digit code is not enough to gain control. The computer also needs to allow the connection. The worst a potential attacker can do is cause a popup on a computer.

**Comment by Warix3** [comment]
Ok, I guess it's safe enough then
