### ISSUE TITLE
Something wrong with my League Client API

### ISSUE THREAD

**Issue by longlearngo** [molenzwiebel/Mimic#34]
Hi, I'm using league client API, realizing your app is a masterpiece. I got inspired by your code, for instance, automatic champion selection. However, when I executed the api, I encountered 500 error. Here is the response of league client:
`{"errorCode":"RPC_ERROR","httpStatus":500,"implementationDetails":{},"message":"Error response for PATCH /lol-lobby-team-builder/champ-select/v1/session/actions/8: Unable to process action change: Received status Error: CHAMPION_ALREADY_PICKED instead of expected status of OK from request to teambuilder-draft:updateActionV1"}`

I coded like this:
```
// ...
var champInfo = { data: qs.stringify({ championId: _self.value }) }
var reqUrl = '/lol-champ-select/v1/session/actions/' + teamInfo[index].cellId
_self.doPatch(reqUrl, champInfo).then((data) => {})

function doPatch (subURL, data) {
      var _self = this
      return new Promise((resolve, reject) => {
        _self.$axios({
          method: 'patch',
          url: 'https://127.0.0.1:' + _self.port + subURL,
          auth: _self.auth,
          data: data
        }).then(response => {
          resolve(response.data)
        }).catch(err => {
          reject(err)
        })
      })
}
```
Could you please check if there is something wrong with my code? Also, I would like to make sure whether I should use cellId to complete the id field? Thank you for your time.

**Comment by aPinat** [comment]
Well, did you read the error message? It literally tells you what's wrong.
So considering, that you get a valid error response, your code should be fine.

**Comment by molenzwiebel** [comment]
We've talked a bit on the Riot developer Discord and this should be solved now. 👌
