### ISSUE TITLE
Vex and Akshan icons don't load during ban phase

### ISSUE THREAD

**Issue by lorenzua02** [molenzwiebel/Mimic#53]
![WhatsApp Image 2021-11-02 at 16 54 17](https://user-images.githubusercontent.com/47902610/139888049-1cbf3b4c-8d90-456b-9ef7-0eb39135f7c0.jpeg)

**Comment by bsk105** [comment]
im having same issue as well.

**Comment by godofgrunts** [comment]
Yeah the manifest needs to be updated. They used to do it occasionally, but they haven't done it in a while.

**Comment by molenzwiebel** [comment]
Should be fixed now, sorry for the delay.
